---

neovim_version: "v0.11.6"
neovim_config_dir: "{{system_config_dir}}/nvim"
neovim_download_url: "https://github.com/neovim/neovim/releases/download/{{neovim_version}}/nvim-linux-x86_64.tar.gz"
neovim_source_dir: "{{system_data_dir}}/nvim-linux-x86_64"
