---

- hosts: localhost
  connection: local
  roles:
    - { role: apt_packages, tags: [dev, apt_packages] }
    - { role: bazelisk, tags: [dev, bazelisk] }
    - { role: neovim, tags: [dev, neovim] }
    - { role: clangd, tags: [never, dev, clangd] }
